---
- name: Install packages
  become: yes
  apt: pkg={{ item }}
  with_items:
    - git
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2
    - python
    - python-dev
    - python-pip
    - libpq-dev
    - libcurl4-openssl-dev
    - librrd-dev
    - libtiff-tools
    - libjpeg-dev
