- name: Create db user
  become: true
  become_user: postgres
  postgresql_user: name={{ db_main_user }} password={{ db_main_pass }}

- name: Create main db
  become: true
  become_user: postgres
  postgresql_db: name={{ db_main_name }} owner={{ db_main_user }}